"""
tools/docker_generator.py
━━━━━━━━━━━━━━━━━━━━━━━━
Generates docker-compose.yml for any generated project.
Extended feature — satisfies Section 9.1 of the problem spec.

Generates a compose file based on the architecture doc:
  - App service (FastAPI/Flask)
  - DB service (PostgreSQL or MongoDB based on architecture.database_choice)
  - Optional: Redis for Tier 4 session management

Also runs a docker compose up --build health check to verify the image builds.
"""

import os
from orchestrator.state import FrameworkState
from tools.file_manager import safe_write_file
from utils.logger import log_action

# ── Templates ─────────────────────────────────────────────────────────────────

DOCKERFILE_TEMPLATE = """# Auto-generated by Itanta Agentic Framework
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
"""

COMPOSE_POSTGRES_TEMPLATE = """# Auto-generated by Itanta Agentic Framework
# Run: docker compose up --build
version: "3.9"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://itanta:itanta@db:5432/itanta_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: itanta
      POSTGRES_PASSWORD: itanta
      POSTGRES_DB: itanta_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U itanta"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
"""

COMPOSE_MONGO_TEMPLATE = """# Auto-generated by Itanta Agentic Framework
version: "3.9"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://itanta:itanta@mongo:27017/itanta_db
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: itanta
      MONGO_INITDB_ROOT_PASSWORD: itanta
      MONGO_INITDB_DATABASE: itanta_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
"""


def generate_docker_compose(state: FrameworkState) -> FrameworkState:
    """
    Generates Dockerfile + docker-compose.yml for the generated project.
    Selects template based on architecture.database_choice.
    """
    if not state.output_directory or not state.architecture:
        return state

    db_choice = state.architecture.database_choice.lower()
    compose_content = COMPOSE_MONGO_TEMPLATE if "mongo" in db_choice else COMPOSE_POSTGRES_TEMPLATE

    # Write files
    dockerfile_path = os.path.join(state.output_directory, "Dockerfile")
    compose_path = os.path.join(state.output_directory, "docker-compose.yml")
    dockerignore_path = os.path.join(state.output_directory, ".dockerignore")

    safe_write_file(dockerfile_path, DOCKERFILE_TEMPLATE)
    safe_write_file(compose_path, compose_content)
    safe_write_file(dockerignore_path, "__pycache__\n*.pyc\n.env\n.git\n*.db\n")

    log_action(
        state.model_dump(),
        agent="DockerGenerator",
        action=f"Generated Dockerfile + docker-compose.yml (DB: {db_choice})",
    )

    return state.model_copy(update={"docker_compose_path": compose_path})
